---
name: "test"
permissions:
  contents: read
  id-token: write
  pull-requests: write


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:

  helm-plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ca-central-1
          role-to-assume: arn:aws:iam::945346656997:role/github-actions-eks-deployment-staging-oidc-github-actions
